[versions]

# build Environmental
compileSdk = "36"
targetSdk = "35"
minSdk = "24"

# library version
androidGradlePlugin = "8.13.2"
androidxAnnotation = "1.9.1"
androidxAppCompat = "1.7.1"
androidxCardview = "1.0.0"
androidxComposeBom = "2025.12.01"
androidxComposeCompiler = "1.5.15"  # use in configureComposeAndroid AndroidCompose.kt
androidxConstaintLayout = "2.2.1"
androidxCoreKtx = "1.17.0"
androidxCoreSplashScreen = "1.2.0"
androidxDataStore = "1.2.0"
androidxFragment = "1.8.9"
androidxHiltNavigationCompose = "1.3.0"
androidxLifecycle = "2.10.0"
androidxNavigation = "2.9.6"
androidxRecyclerView = "1.4.0"
androidxRoom = "2.8.4"
androidxStartUp = "1.2.0"
androidxTestEspresso = "3.7.0"
androidxTestJunit = "1.3.0"
androidxTestRules = "1.7.0"
androidxTransition = "1.7.0"
appCashTurbine = "1.2.0"
coil = "2.7.0"
desugarJdklibs = "2.1.5"
googleHilt = "2.58"
googleMaterial = "1.13.0"
googlePlayServicesTime = "16.0.1"
jacoco = "0.8.14" # use in configureJacocoToolVersion -> Jacoco.kt
javafaker = "1.0.2"
jsoup = "1.22.1"
junit = "4.13.2"
kotlin = "2.2.21"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJson = "1.9.0"
ksp = "2.3.4"
kotlinxCollectionsImmutable = "0.4.0"
kotlinxCoroutine = "1.10.2"
mockk = "1.14.7"
squareLeakcanary = "2.14"
timber = "5.0.1"
turbine = "1.2.1"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidxAnnotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppCompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidxCardview" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" } # use in configureComposeAndroid AndroidCompose.kt
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" } # use in configureComposeAndroid AndroidCompose.kt
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }    # use in configureStdComposeDependencies AndroidComposeDependencies.kt
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-constaintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstaintLayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxCoreSplashScreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDataStore" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-fragment-compose = { module = "androidx.fragment:fragment-compose", version.ref = "androidxFragment"  }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidxRecyclerView" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "androidxStartUp" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspresso" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTestRules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRules" }
androidx-transition-ktx = { module = "androidx.transition:transition-ktx", version.ref = "androidxTransition" }
coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-kt-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdklibs" }  # use in configureComposeAndroid KotlinOptions.kt
google-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "googleHilt" }       # use in nlab.android.hilt.gradle.kts
google-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "googleHilt" }     # use in nlab.android.hilt.gradle.kts
google-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }
google-play-services-time = { module = "com.google.android.gms:play-services-time", version.ref = "googlePlayServicesTime" }
javafaker = { module = "com.github.javafaker:javafaker", version.ref = "javafaker" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutine" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutine" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutine" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
squeare-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "squareLeakcanary" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

# Dependencies of the included build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
compose-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-hilt = { id = "com.google.dagger.hilt.android", version.ref = "googleHilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# Plugins defined by this project
nlab-android-application = { id = "nlab.android.application" }
nlab-android-application-compose = { id = "nlab.android.application.compose" }
nlab-android-application-jacoco = { id = "nlab.android.application.jacoco" }
nlab-android-hilt = { id = "nlab.android.hilt" }
nlab-android-library = { id = "nlab.android.library" }
nlab-android-library-component = { id = "nlab.android.library.component" }
nlab-android-library-compose = { id = "nlab.android.library.compose" }
nlab-android-library-feature = { id = "nlab.android.library.feature" }
nlab-android-library-di = { id = "nlab.android.library.di" }
nlab-android-library-jacoco = { id = "nlab.android.library.jacoco" }
nlab-android-library-statekit = { id = "nlab.android.library.statekit" }
nlab-jvm-library = { id = "nlab.jvm.library" }
nlab-jvm-library-jacoco = { id = "nlab.jvm.library.jacoco" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }